name: flutter_graphql_todo_app
description: A todo application with flutter and graphql

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ferry: ^0.10.3
  ferry_flutter: ^0.5.3
  hive: ^2.0.4
  hive_flutter: 1.0.0
  ferry_hive_store: ^0.4.3
  gql_http_link: ^0.4.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  ferry_generator: ^0.4.3
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true